name: Pearls Train + Predict

on:
  schedule:
    - cron: "5 0 * * *"   # 5 minutes after midnight (VERY IMPORTANT)
  workflow_dispatch:

jobs:
  train_predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # TRAIN
      - name: Run training pipeline
        run: python -m models.train_model
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      # PREDICT
      - name: Run prediction pipeline
        run: python predict.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
